#!/bin/bash

VER=4.1.1
rm -f translation_$VER.jar

mkdir -p build 2>/dev/null
cp -Rf translation_$VER/translation build/

cd translation_$VER
echo 1
find translation -name '*.properties' -exec native2ascii -encoding UTF-8 {} ../build/{} \;
cd ..

cd build/translation
echo 2
find com -name '*.translation' -exec bash -c 'awk '"'"'BEGIN {RS="\r?\n";ORS="";FS="\t"} $2!="" {print $0 "\r\n"; next} {print $1 "\t" $1 "\r\n"}'"'"' < {} > {}.tmp' \;
echo 3
find com -name '*.translation.tmp' -exec rename .translation.tmp .class '{}' \;
echo 4
find com -name '*.translation' -exec rm -f {} \;
echo 5
zip -r ../../translation_$VER.jar com
cd ../..

cp -f translation_$VER.jar loc_hack/src/translation.jar
ln -sf loc_hack/src/translation.jar translation.jar

rm -Rf translation_$VER/translation_jar/com
cp -lRf build/translation/com translation_$VER/translation_jar/
rm -Rf build/translation
